import 'package:logaluxe_users/model/category.dart';
import 'package:logaluxe_users/model/service.dart';
import 'package:logaluxe_users/model/user.dart';

List<ServiceModel> allServices = [
  ServiceModel(
      id: "679941bd1b67b20060368693",
      country: "nigeria",
      state: "adamawa state",
      opening_time: "10am",
      closing_time: "10pm",
      name: "Skin care",
      service_duration: "45",
      description: "A blunt cut bob is a shorter hairstyle that's c..",
      location: "Ibadan",
      amount: 1000,
      image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668742/kcivpncdwqqd5xlnfrhb.jpg",
      category_id: CategoryModel(id: "id", category_name: "category_name", category_ref: "category_ref"),
      currency: "\$",
      company_id: UserModel(
          id: '',
          email: "jane.smith@salon.com",
          first_name: 'first_name',
          bio: 'bio',
          business_name: 'business_name',
          business_address: 'business_address',
          company_id: 'company_id',
          token: 'token'),
      service_ref: "1SER-7IEE",
      createdAt: "2025-01-28T20:44:45.594Z",
      updatedAt: "2025-02-19T18:35:22.626Z",
      active: false),
  ServiceModel(
      id: "679941bd1b67b20060368693",
      country: "nigeria",
      state: "adamawa state",
      opening_time: "10am",
      closing_time: "10pm",
      name: "Furniture care",
      service_duration: "45",
      description: "A blunt cut bob is a shorter hairstyle that's c..",
      location: "Ibadan",
      amount: 1000,
      image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668782/t6uugitpty9oyiq0n1zh.jpg",
      category_id: CategoryModel(id: "id", category_name: "category_name", category_ref: "category_ref"),
      currency: "\$",
      company_id: UserModel(
          id: '',
          first_name: 'first_name',
          bio: 'bio',
          business_name: 'business_name',
          email: "jane.smith@salon.com",
          business_address: 'business_address',
          company_id: 'company_id',
          token: 'token'),
      service_ref: "2SER-7IEE",
      createdAt: "2025-01-28T20:44:45.594Z",
      updatedAt: "2025-02-19T18:35:22.626Z",
      active: false),
  ServiceModel(
      id: "679941bd1b67b20060368693",
      country: "nigeria",
      state: "adamawa state",
      opening_time: "10am",
      closing_time: "10pm",
      name: "Skin care",
      service_duration: "45",
      description: "A blunt cut bob is a shorter hairstyle that's c..",
      location: "Ibadan",
      amount: 1000,
      image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668893/tt8sxlqjfz8pokh9kayc.jpg",
      category_id: CategoryModel(id: "id", category_name: "category_name", category_ref: "category_ref"),
      currency: "\$",
      company_id: UserModel(
          id: '',
          first_name: 'first_name',
          bio: 'bio',
          business_name: 'business_name',
          email: "jane.smith@salon.com",
          business_address: 'business_address',
          company_id: 'company_id',
          token: 'token'),
      service_ref: "3SER-7IEE",
      createdAt: "2025-01-28T20:44:45.594Z",
      updatedAt: "2025-02-19T18:35:22.626Z",
      active: false),
  ServiceModel(
      id: "679941bd1b67b20060368693",
      country: "nigeria",
      state: "adamawa state",
      opening_time: "10am",
      closing_time: "10pm",
      name: "Skin care",
      service_duration: "45",
      description: "A blunt cut bob is a shorter hairstyle that's c..",
      location: "Ibadan",
      amount: 1000,
      image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668810/csddbfk0oc8z0xsi6aty.jpg",
      category_id: CategoryModel(id: "id", category_name: "category_name", category_ref: "category_ref"),
      currency: "\$",
      company_id: UserModel(
          id: '',
          first_name: 'first_name',
          bio: 'bio',
          business_name: 'business_name',
          business_address: 'business_address',
          company_id: 'company_id',
          email: "jane.smith@salon.com",
          token: 'token'),
      service_ref: "4SER-7IEE",
      createdAt: "2025-01-28T20:44:45.594Z",
      updatedAt: "2025-02-19T18:35:22.626Z",
      active: false),
  ServiceModel(
      id: "679941bd1b67b20060368693",
      country: "nigeria",
      state: "adamawa state",
      opening_time: "10am",
      closing_time: "10pm",
      name: "Skin care",
      service_duration: "45",
      description: "A blunt cut bob is a shorter hairstyle that's c..",
      location: "Ibadan",
      amount: 1000,
      image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668837/xjvd7fnacog72xk1thxb.jpg",
      category_id: CategoryModel(id: "id", category_name: "category_name", category_ref: "category_ref"),
      currency: "\$",
      company_id: UserModel(
          id: '',
          first_name: 'first_name',
          email: "jane.smith@salon.com",
          bio: 'bio',
          business_name: 'business_name',
          business_address: 'business_address',
          company_id: 'company_id',
          token: 'token'),
      service_ref: "5SER-7IEE",
      createdAt: "2025-01-28T20:44:45.594Z",
      updatedAt: "2025-02-19T18:35:22.626Z",
      active: false),
  ServiceModel(
      id: "679941bd1b67b20060368693",
      country: "nigeria",
      state: "adamawa state",
      opening_time: "10am",
      closing_time: "10pm",
      name: "Skin care",
      service_duration: "45",
      description: "A blunt cut bob is a shorter hairstyle that's c..",
      location: "Ibadan",
      amount: 1000,
      image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668865/t0tqapqkm8ingozkmzir.jpg",
      category_id: CategoryModel(id: "id", category_name: "category_name", category_ref: "category_ref"),
      currency: "\$",
      company_id: UserModel(
          id: '',
          first_name: 'first_name',
          email: "jane.smith@salon.com",
          bio: 'bio',
          business_name: 'business_name',
          business_address: 'business_address',
          company_id: 'company_id',
          token: 'token'),
      service_ref: "6SER-7IEE",
      createdAt: "2025-01-28T20:44:45.594Z",
      updatedAt: "2025-02-19T18:35:22.626Z",
      active: false)
];
