import 'package:logaluxe_users/model/user.dart';

List<UserModel> allUsers = [
  UserModel(
    id: '',
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    token: "",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668742/kcivpncdwqqd5xlnfrhb.jpg",
    bio:
        "Living up to our name Logaluxe, the team is highly energetic and creative. We believe that if it matters to you, it matters to us. Keeping up to speed with the market\’s latest trends, Logaluxe recognizes the need for constant improvements. Our team receives regular training from hairdressers all...  Read more",
    availability: true,
    subscription_plan: null,
    opening_time: "3am",
    closing_time: "9pm",
    business_name: "Chris Beauty Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: '',
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    id: '',
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    token: "",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668782/t6uugitpty9oyiq0n1zh.jpg",
    bio:
        "Living up to our name Logaluxe, the team is highly energetic and creative. We believe that if it matters to you, it matters to us. Keeping up to speed with the market\’s latest trends, Logaluxe recognizes the need for constant improvements. Our team receives regular training from hairdressers all...  Read more",
    availability: true,
    subscription_plan: null,
    opening_time: "3am",
    closing_time: "9pm",
    business_name: "Hubs and Shaw Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: '',
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    id: '',
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    token: "",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668893/tt8sxlqjfz8pokh9kayc.jpg",
    bio:
        "Living up to our name Logaluxe, the team is highly energetic and creative. We believe that if it matters to you, it matters to us. Keeping up to speed with the market\’s latest trends, Logaluxe recognizes the need for constant improvements. Our team receives regular training from hairdressers all...  Read more",
    availability: true,
    subscription_plan: null,
    opening_time: "3am",
    closing_time: "9pm",
    business_name: "Logaluxe saloon Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: '',
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    id: '',
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    token: "",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668810/csddbfk0oc8z0xsi6aty.jpg",
    bio:
        "Living up to our name Logaluxe, the team is highly energetic and creative. We believe that if it matters to you, it matters to us. Keeping up to speed with the market\’s latest trends, Logaluxe recognizes the need for constant improvements. Our team receives regular training from hairdressers all...  Read more",
    availability: true,
    subscription_plan: null,
    opening_time: "3am",
    closing_time: "9pm",
    business_name: "Beauty hub Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: '',
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    id: '',
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    token: "",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668837/xjvd7fnacog72xk1thxb.jpg",
    bio:
        "Living up to our name Logaluxe, the team is highly energetic and creative. We believe that if it matters to you, it matters to us. Keeping up to speed with the market\’s latest trends, Logaluxe recognizes the need for constant improvements. Our team receives regular training from hairdressers all...  Read more",
    availability: true,
    subscription_plan: null,
    opening_time: "3am",
    closing_time: "9pm",
    business_name: "Walmart store Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: '',
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    id: '',
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    token: "",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668865/t0tqapqkm8ingozkmzir.jpg",
    bio:
        "Living up to our name Logaluxe, the team is highly energetic and creative. We believe that if it matters to you, it matters to us. Keeping up to speed with the market\’s latest trends, Logaluxe recognizes the need for constant improvements. Our team receives regular training from hairdressers all...  Read more",
    availability: true,
    subscription_plan: null,
    opening_time: "3am",
    closing_time: "9pm",
    business_name: "Google Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: '',
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    id: '',
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    token: "",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668893/tt8sxlqjfz8pokh9kayc.jpg",
    bio:
        "Living up to our name Logaluxe, the team is highly energetic and creative. We believe that if it matters to you, it matters to us. Keeping up to speed with the market\’s latest trends, Logaluxe recognizes the need for constant improvements. Our team receives regular training from hairdressers all...  Read more",
    availability: true,
    subscription_plan: null,
    opening_time: "3am -",
    closing_time: "e 9pm",
    business_name: "Eleganza saloon Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: '',
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    id: '',
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    token: "",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668893/tt8sxlqjfz8pokh9kayc.jpg",
    bio:
        "Living up to our name Logaluxe, the team is highly energetic and creative. We believe that if it matters to you, it matters to us. Keeping up to speed with the market\’s latest trends, Logaluxe recognizes the need for constant improvements. Our team receives regular training from hairdressers all...  Read more",
    availability: true,
    subscription_plan: null,
    opening_time: "3am ",
    closing_time: "9pm",
    business_name: "Santa beauty Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: '',
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    id: '',
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    token: "",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668837/xjvd7fnacog72xk1thxb.jpg",
    bio:
        "Living up to our name Logaluxe, the team is highly energetic and creative. We believe that if it matters to you, it matters to us. Keeping up to speed with the market\’s latest trends, Logaluxe recognizes the need for constant improvements. Our team receives regular training from hairdressers all...  Read more",
    availability: true,
    subscription_plan: null,
    opening_time: "3am ",
    closing_time: "9pm",
    business_name: "Plush Beauty Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: '',
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
];
