import 'package:logaluxe_users/model/user.dart';

List<UserModel> allUsers = [
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "https://beauty-hub-api.onrender.com/api/v1/auth/storage/uploads/1740095485960.png",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am",
    closing_time: "close 9pm",
    business_name: "Chris Beauty",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "https://beauty-hub-api.onrender.com/api/v1/auth/storage/uploads/1740095485960.png",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Hubs and Shaw",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "https://beauty-hub-api.onrender.com/api/v1/auth/storage/uploads/1740095485960.png",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Logaluxe saloon",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "https://beauty-hub-api.onrender.com/api/v1/auth/storage/uploads/1740095485960.png",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Beauty hub",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "https://beauty-hub-api.onrender.com/api/v1/auth/storage/uploads/1740095485960.png",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Walmart store",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "https://beauty-hub-api.onrender.com/api/v1/auth/storage/uploads/1740095485960.png",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Google",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "https://beauty-hub-api.onrender.com/api/v1/auth/storage/uploads/1740095485960.png",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Eleganza saloon",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "https://beauty-hub-api.onrender.com/api/v1/auth/storage/uploads/1740095485960.png",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Santa beauty",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "https://beauty-hub-api.onrender.com/api/v1/auth/storage/uploads/1740095485960.png",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Plush Beauty",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
];
