import 'package:logaluxe_users/model/user.dart';

List<UserModel> allUsers = [
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668742/kcivpncdwqqd5xlnfrhb.jpg",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am",
    closing_time: "close 9pm",
    business_name: "Chris Beauty Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668782/t6uugitpty9oyiq0n1zh.jpg",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Hubs and Shaw Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668893/tt8sxlqjfz8pokh9kayc.jpg",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Logaluxe saloon Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668810/csddbfk0oc8z0xsi6aty.jpg",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Beauty hub Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668837/xjvd7fnacog72xk1thxb.jpg",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Walmart store Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668865/t0tqapqkm8ingozkmzir.jpg",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Google Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668893/tt8sxlqjfz8pokh9kayc.jpg",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Eleganza saloon Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668893/tt8sxlqjfz8pokh9kayc.jpg",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Santa beauty Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
  UserModel(
    first_name: "joshn",
    last_name: "john",
    email: "owoeye1321@gmail.com",
    phone: "09176546374",
    occupation: "data science",
    is_active: true,
    email_verification_code: "R948",
    two_fa_code: "AQYRBGNUJG",
    salt: "dc8b1093e57f1264fb243a06d8683b68",
    otp: null,
    image_url: "http://res.cloudinary.com/dkr0odvfi/image/upload/v1740668837/xjvd7fnacog72xk1thxb.jpg",
    bio: null,
    availability: true,
    subscription_plan: null,
    opening_time: "open 3am -",
    closing_time: " close 9pm",
    business_name: "Plush Beauty Hub Abuja",
    business_address: "No 3 Asokor joint, off CBDA",
    company_id: null,
    is_email_verified: false,
    is_phone_verified: false,
    otp_expiry: null,
    country: "string",
    subscription_expiry_date: null,
    state: "string",
    currency: null,
    role: "customer",
    customer_ref: "CUS-PFS48Q",
    city: null,
    postal_code: "string",
  ),
];
