// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlXoc8hMfcbRUgGWjO3bDt0JuE6GOB_Zo',
    appId: '1:763655628817:web:d9aa2fb8e132117c4aa9b0',
    messagingSenderId: '763655628817',
    projectId: 'logaluxe-8c36e',
    authDomain: 'logaluxe-8c36e.firebaseapp.com',
    storageBucket: 'logaluxe-8c36e.firebasestorage.app',
    measurementId: 'G-G34JBQ10H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS2L1WC1HHMc3PPf64ZN0D-TYGILhYIOE',
    appId: '1:763655628817:android:9a3b08a14fd897d64aa9b0',
    messagingSenderId: '763655628817',
    projectId: 'logaluxe-8c36e',
    storageBucket: 'logaluxe-8c36e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAPPp-4OXAuEMHw6q7mmguYHk0FdeMVVc',
    appId: '1:763655628817:ios:568287125d8091074aa9b0',
    messagingSenderId: '763655628817',
    projectId: 'logaluxe-8c36e',
    storageBucket: 'logaluxe-8c36e.firebasestorage.app',
    iosClientId: '763655628817-ra1ldjba8m7agp1bpvb39pci2bhrqsl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.logaluxeUsers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAPPp-4OXAuEMHw6q7mmguYHk0FdeMVVc',
    appId: '1:763655628817:ios:568287125d8091074aa9b0',
    messagingSenderId: '763655628817',
    projectId: 'logaluxe-8c36e',
    storageBucket: 'logaluxe-8c36e.firebasestorage.app',
    iosClientId: '763655628817-ra1ldjba8m7agp1bpvb39pci2bhrqsl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.logaluxeUsers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlXoc8hMfcbRUgGWjO3bDt0JuE6GOB_Zo',
    appId: '1:763655628817:web:4c8e6ede84ec63ad4aa9b0',
    messagingSenderId: '763655628817',
    projectId: 'logaluxe-8c36e',
    authDomain: 'logaluxe-8c36e.firebaseapp.com',
    storageBucket: 'logaluxe-8c36e.firebasestorage.app',
    measurementId: 'G-1GMH75JCGS',
  );
}
